### ISSUE TITLE
Why there is a few days receive time difference between close in time custom events?

### ISSUE THREAD

**Issue by nominalista** [getsentry/sentry-android#360]
I log user in-app behavior with Sentry and I've noticed that some of the events are received in a few days delay.

E.g. there are 3 events - `EventA`, `EventB`, `EventC`. 

`EventA` was created at 01:00:00 PM, 1 August.
`EventB` was created at 01:00:05 PM, 1 August.
`EventC` was created at 01:00:10 PM, 1 August.

As you can see, they were sent in the same second. But, they were received in a one day difference.

`EventA` was received at 01:01:00 PM, 1 August.
`EventB` was received at 03:00:00 PM, 2 August.
`EventC` was received at 06:00:00 PM, 3 August.

Moreover, there was a stable network connection, because `EventA` was sent almost immediately. Of course presented timestamps are just examples, but they show the exact problem I experienced.

Are there any default preferences in SDK that may produce such behavior?

**Comment by marandaneto** [comment]
hey @nominalista thanks for your message.

Events should be sent right away if there's network connection, although if there's a crash or segfault(NDK), it might only send on App. restart due to resource limitations.

If it was not possible, it's gonna try to send it again on App. restart, if on App restart there's no network available, on the next App. restart again and so on.

That means if the App. crashed and the user didn't open it again, it might have a delay until the user does so.

If all the conditions were met and still you didn't see the event coming thru, It'd be helpful to get a repro case where we can test and debug it.

Does that answer you? Thanks :)

**Comment by nominalista** [comment]
Hi @marandaneto, unfortunately, looking on other events that were created soon after, app didn't crash, but I can imagine there were some issues with access to memory by SDK. 

Is it possible and is it a good practice to send cached events periodically (by using e.g. WorkManager) so I could see events in console earlier?

**Comment by marandaneto** [comment]
@nominalista connection is not stable 24h a day, so it might be the case that it was just unstable at that given moment.

We intend to not bring dependencies in eg `WorkManager`, but of course, we can have our own, as we already do eg `SendCachedEventFireAndForgetIntegration`.

Sending events periodically is a nice idea though, I'll consider that as a feature request, would you mind opening a new issue for that and close this one if your question has been answered? just to keep the issue short and clean, thanks :)
